name: Require Changeset
description: "Fail PRs to main without a changeset (skip for release PRs)"
runs:
  using: composite
  steps:
    - name: Check for changeset in PR
      shell: bash
      run: |
        echo "PR title: ${{ github.event.pull_request.title }}"
        echo "Actor: ${{ github.actor }}"

        # Skip guard for release PRs created by Changesets
        if [[ "${{ github.event.pull_request.title }}" == "Version Packages"* ]] \
           || [[ "${{ github.actor }}" == "github-actions[bot]" ]]; then
          echo "ℹ️ Release PR detected, skipping changeset check."
          exit 0
        fi

        git fetch origin main
        MB=$(git merge-base origin/main HEAD)

        if ! git diff --name-only $MB...HEAD | grep -qE '^\.changeset/.*\.md$'; then
          echo "❌ No changeset found. Add one with: pnpm changeset"
          exit 1
        fi

        echo "✅ Changeset found."