name: Build, Lint, and Test
description: A composite action to build, lint, and test the project
runs:
  using: composite
  steps:
    - name: list actions
      shell: bash
      run: grep -RIn "upload-artifact@v4\|dist-packages\|packages/lib-one/dist\|packages/lib-two/dist" .github

    - name: Build packages
      shell: bash
      run: pnpm -r build

    - name: Lint code
      shell: bash
      run: pnpm -r lint

    - name: Run tests
      shell: bash
      run: pnpm -r test