name: Build, Lint, and Test
description: A composite action to build, lint, and test the project
runs:
  using: composite
  steps:
    - name: Build packages
      shell: bash
      run: pnpm -r build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        if-no-files-found: error
        retention-days: 1
        path: packages/*/dist/

    - name: Lint code
      shell: bash
      run: pnpm -r lint

    - name: Run tests
      shell: bash
      run: pnpm -r test -- --ci --coverage

    # Download previous coverage for diff comparison (PRs only)
    - name: Download baseline coverage
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/download-artifact@v4
      with:
        name: coverage-baseline
        path: baseline-coverage
      continue-on-error: true

    # This script gathers coverage-summary.json per package and also copies
    # lcov.info + full HTML reports into coverage-artifacts/<pkg>/
    # Also handles diff comparison if baseline is available
    - name: Collect coverage summaries
      shell: bash
      env:
        OUT_DIR: coverage-artifacts
        COVERAGE_FILE_NAME: coverage-summary.json
        ENABLE_COVERAGE_DIFF: ${{ github.event_name == 'pull_request' && 'true' || 'false' }}
        BASELINE_ARTIFACT_PATH: ${{ github.event_name == 'pull_request' && 'baseline-coverage' || '' }}
      run: node .github/scripts/collect-coverage.js

    # Upload lightweight JSON + Markdown summary
    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-artifacts
        path: coverage-artifacts/**

    # Save coverage as baseline for future PR comparisons (main branch only)
    - name: Upload coverage baseline
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: coverage-baseline
        path: coverage-artifacts/**
        retention-days: 90

    # Sticky comment on PR
    - name: Post/update sticky coverage comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: coverage-report
        path: coverage-artifacts/coverage-report.md
      