on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - name : Lint code
        run: pnpm -r lint
      - name: Build packages
        run: pnpm -r build
      - name: Run tests
        run: pnpm -r test