name: main
on:
  workflow_run:
    workflows: ["Prepare"]
    types: [completed]
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false # so we control the push identity
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/require-changeset
        with:
          skip-label: "[skip changeset check]"

      - uses: ./.github/actions/build-lint-test

  codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      # This permissions are required by codeql workflow
      security-events: write
      pull-requests: write
      contents: read
    with: 
      languages: 'javascript' # comma separated values code

  publish:
    needs: build
    name: publish
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # Grants write access to the GitHub Actions workflow's OIDC token, enabling authentication with external services.
      id-token: write 
      pull-requests: write
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false # so we control the push identity
      
      # Setup Node.js with pnpm
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}

       # Configure git identity and GPG signing for release commits
      - uses: ./.github/actions/setup-ci-git-identity
        with:
          purpose: 'GPG-signed release commits'
          enable-gpg-signing: 'true'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Set up authentication to push changes using the bot / pat token
      - name: Set up auth with bot token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/${{ github.repository }}.git

      # Debugging step to verify git identity configuration
      - name: Debug commit identity
        run: |
          echo "Git identity:"
          git config --get user.name
          git config --get user.email
          echo "Env identity:"
          env | grep -E 'GIT_(AUTHOR|COMMITTER)_' || true
      # Download build artifacts to the 'packages' directory
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: dist-packages
          path: packages
      
     # Add a debugging step to list the contents of the packages directory
      - name: Debug downloaded artifacts
        run: |
          echo "Contents after artifact download:"
          find packages -name "*.js" -o -name "*.mjs" -o -name "*.d.ts" | head -10
          echo "Package directories:"
          ls -la packages/*/dist/ 2>/dev/null || echo "No dist directories found"

      # Create Release Pull Request or Publish
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: 'pnpm run release'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Debugging step to show the latest commit with signature info
      - name: Show latest commit + signature
        run: |
          echo "Latest commit with signature info:"
          git --no-pager log -1 --pretty=full --show-signature