name: publish
on:
  push:
    branches: [ main ]
concurrency: ${{ github.workflow }}-${{ github.ref_name }}

permissions:
  contents: write
  id-token: write              # npm provenance (OIDC)
  pull-requests: write

jobs:
  publish:
    if: ${{ github.event.workflow.conclusion != 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v2
        with:
          publish: 'pnpm run release'
      
